<<<<<<< HEAD
ï»¿apiVersion: kustomize.toolkit.fluxcd.io/v1
=======
apiVersion: kustomize.toolkit.fluxcd.io/v1
>>>>>>> bfed36e0233e49b33a709ba031924e2624f4c734
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 1m
  path: ./apps/podinfo
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
<<<<<<< HEAD
=======

>>>>>>> bfed36e0233e49b33a709ba031924e2624f4c734
